name: Integracion Continua Docker

on:
  push:
    branches: [ "main" ]

jobs:
  construir-y-probar:
    runs-on: ubuntu-latest
    
    steps:
    - name: Descargar el codigo del repositorio
      uses: actions/checkout@v4

    - name: Construir la imagen de Docker
      run: docker build -t mi-api-mlops .
